In [1]:
!pwd

/Users/matthewbaxter/Documents/obds_course_exrecises/Week_2

In [2]:
import numpy as np
import pandas as pd

In [9]:
gtf = pd.read_csv('Homo_sapiens.GRCh38.107.gtf.gz', sep='\t', header = None, comment='#')

/var/folders/ln/b27g5h050b7c4j9sh03qk90c0000gr/T/ipykernel_96485/2357806593.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  gtf = pd.read_csv('Homo_sapiens.GRCh38.107.gtf.gz', sep='\t', header = None, comment='#')

In [10]:
gtf.head()

,0,1,2,3,4,5,6,7,8
0,1,ensembl_havana,gene,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
1,1,ensembl_havana,transcript,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
2,1,ensembl_havana,exon,1471765,1472089,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
3,1,ensembl_havana,CDS,1471885,1472089,.,+,0,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
4,1,ensembl_havana,start_codon,1471885,1471887,.,+,0,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."

In [11]:
gtf.shape

(3371244, 9)

# Assign column names

In [14]:
gtf.columns=['seqname', 'source' , 'feature' , 'start' , 'end', 'score' , 'strand' ,  'frame' ,  'attribute' ]

In [15]:
gtf.head()

,seqname,source,feature,start,end,score,strand,frame,attribute
0,1,ensembl_havana,gene,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
1,1,ensembl_havana,transcript,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
2,1,ensembl_havana,exon,1471765,1472089,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
3,1,ensembl_havana,CDS,1471885,1472089,.,+,0,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
4,1,ensembl_havana,start_codon,1471885,1471887,.,+,0,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."

# How many unique values for ‘source’ column?

In [17]:
gtf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3371244 entries, 0 to 3371243
Data columns (total 9 columns):
 #   Column     Dtype
---  ------     -----
 0   seqname    object
 1   source     object
 2   feature    object
 3   start      int64
 4   end        int64
 5   score      object
 6   strand     object
 7   frame      object
 8   attribute  object
dtypes: int64(2), object(7)
memory usage: 231.5+ MB

In [18]:
gtf["source"].unique()

array(['ensembl_havana', 'havana', 'ensembl', 'havana_tagene',
       'ensembl_havana_tagene', 'mirbase', 'ensembl_tagene', 'insdc'],
      dtype=object)

# Subset all values from ‘ensembl_havana’ and assign to new df called ‘ens_df’

In [28]:
ens_gtf = gtf[gtf["source"].str.contains("ensembl_havana")]
ens_gtf

,seqname,source,feature,start,end,score,strand,frame,attribute
0,1,ensembl_havana,gene,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
1,1,ensembl_havana,transcript,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
2,1,ensembl_havana,exon,1471765,1472089,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
3,1,ensembl_havana,CDS,1471885,1472089,.,+,0,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
4,1,ensembl_havana,start_codon,1471885,1471887,.,+,0,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
...,...,...,...,...,...,...,...,...,...
3370044,21,ensembl_havana,exon,46445284,46445769,.,+,.,"gene_id ""ENSG00000160299""; gene_version ""19""; ..."
3370045,21,ensembl_havana,CDS,46445284,46445324,.,+,2,"gene_id ""ENSG00000160299""; gene_version ""19""; ..."
3370046,21,ensembl_havana,stop_codon,46445325,46445327,.,+,0,"gene_id ""ENSG00000160299""; gene_version ""19""; ..."
3370047,21,ensembl_havana,five_prime_utr,46324156,46324228,.,+,.,"gene_id ""ENSG00000160299""; gene_version ""19""; ..."
3370048,21,ensembl_havana,three_prime_utr,46445328,46445769,.,+,.,"gene_id ""ENSG00000160299""; gene_version ""19""; ..."

# What is the size of ens_df?

In [27]:
ens_gtf.shape

(714883, 9)

# Group ens_df by ‘feature’ column & apply the ‘count’ function to get the number of rows in each feature

In [33]:
(ens_gtf.groupby("feature")
   .count() 
)

,seqname,source,start,end,score,strand,frame,attribute
feature,,,,,,,,
CDS,262675,262675,262675,262675,262675,262675,262675,262675
Selenocysteine,13,13,13,13,13,13,13,13
exon,286002,286002,286002,286002,286002,286002,286002,286002
five_prime_utr,38189,38189,38189,38189,38189,38189,38189,38189
gene,19290,19290,19290,19290,19290,19290,19290,19290
start_codon,25891,25891,25891,25891,25891,25891,25891,25891
stop_codon,25908,25908,25908,25908,25908,25908,25908,25908
three_prime_utr,30120,30120,30120,30120,30120,30120,30120,30120
transcript,26795,26795,26795,26795,26795,26795,26795,26795

# Create a new df called ‘genes’ by subsetting all rows with ‘gene’ as a feature

In [34]:
genes = ens_gtf[ens_gtf["feature"].str.contains("gene")]

In [35]:
genes

,seqname,source,feature,start,end,score,strand,frame,attribute
0,1,ensembl_havana,gene,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ..."
132,1,ensembl_havana,gene,3069168,3438621,.,+,.,"gene_id ""ENSG00000142611""; gene_version ""17""; ..."
361,1,ensembl_havana,gene,2403964,2413797,.,-,.,"gene_id ""ENSG00000157911""; gene_version ""11""; ..."
517,1,ensembl_havana,gene,2228319,2310213,.,+,.,"gene_id ""ENSG00000157933""; gene_version ""10""; ..."
580,1,ensembl_havana,gene,10472288,10630758,.,+,.,"gene_id ""ENSG00000142655""; gene_version ""13""; ..."
...,...,...,...,...,...,...,...,...,...
3365880,21,ensembl_havana,gene,6318378,6360415,.,+,.,"gene_id ""ENSG00000278903""; gene_version ""5""; g..."
3365953,21,ensembl_havana,gene,33915534,33977703,.,+,.,"gene_id ""ENSG00000237945""; gene_version ""9""; g..."
3367972,21,ensembl_havana,gene,9068325,9129773,.,-,.,"gene_id ""ENSG00000188681""; gene_version ""13""; ..."
3368345,21,ensembl_havana,gene,14236206,14362754,.,+,.,"gene_id ""ENSG00000243064""; gene_version ""10""; ..."
3369764,21,ensembl_havana,gene,46324124,46445769,.,+,.,"gene_id ""ENSG00000160299""; gene_version ""19""; ..."

# Create a new column called ‘gene_length’ and calculate the length of each gene

In [37]:
genes["gene_length"] = genes["end"] - genes["start"]
genes

/var/folders/ln/b27g5h050b7c4j9sh03qk90c0000gr/T/ipykernel_96485/4221030734.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genes["gene_length"] = genes["end"] - genes["start"]

,seqname,source,feature,start,end,score,strand,frame,attribute,gene_length
0,1,ensembl_havana,gene,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ...",26083
132,1,ensembl_havana,gene,3069168,3438621,.,+,.,"gene_id ""ENSG00000142611""; gene_version ""17""; ...",369453
361,1,ensembl_havana,gene,2403964,2413797,.,-,.,"gene_id ""ENSG00000157911""; gene_version ""11""; ...",9833
517,1,ensembl_havana,gene,2228319,2310213,.,+,.,"gene_id ""ENSG00000157933""; gene_version ""10""; ...",81894
580,1,ensembl_havana,gene,10472288,10630758,.,+,.,"gene_id ""ENSG00000142655""; gene_version ""13""; ...",158470
...,...,...,...,...,...,...,...,...,...,...
3365880,21,ensembl_havana,gene,6318378,6360415,.,+,.,"gene_id ""ENSG00000278903""; gene_version ""5""; g...",42037
3365953,21,ensembl_havana,gene,33915534,33977703,.,+,.,"gene_id ""ENSG00000237945""; gene_version ""9""; g...",62169
3367972,21,ensembl_havana,gene,9068325,9129773,.,-,.,"gene_id ""ENSG00000188681""; gene_version ""13""; ...",61448
3368345,21,ensembl_havana,gene,14236206,14362754,.,+,.,"gene_id ""ENSG00000243064""; gene_version ""10""; ...",126548
3369764,21,ensembl_havana,gene,46324124,46445769,.,+,.,"gene_id ""ENSG00000160299""; gene_version ""19""; ...",121645

In [38]:
genes = genes.assign(gene_length = genes['end'] - genes['start'], 
                    )
genes

,seqname,source,feature,start,end,score,strand,frame,attribute,gene_length
0,1,ensembl_havana,gene,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ...",26083
132,1,ensembl_havana,gene,3069168,3438621,.,+,.,"gene_id ""ENSG00000142611""; gene_version ""17""; ...",369453
361,1,ensembl_havana,gene,2403964,2413797,.,-,.,"gene_id ""ENSG00000157911""; gene_version ""11""; ...",9833
517,1,ensembl_havana,gene,2228319,2310213,.,+,.,"gene_id ""ENSG00000157933""; gene_version ""10""; ...",81894
580,1,ensembl_havana,gene,10472288,10630758,.,+,.,"gene_id ""ENSG00000142655""; gene_version ""13""; ...",158470
...,...,...,...,...,...,...,...,...,...,...
3365880,21,ensembl_havana,gene,6318378,6360415,.,+,.,"gene_id ""ENSG00000278903""; gene_version ""5""; g...",42037
3365953,21,ensembl_havana,gene,33915534,33977703,.,+,.,"gene_id ""ENSG00000237945""; gene_version ""9""; g...",62169
3367972,21,ensembl_havana,gene,9068325,9129773,.,-,.,"gene_id ""ENSG00000188681""; gene_version ""13""; ...",61448
3368345,21,ensembl_havana,gene,14236206,14362754,.,+,.,"gene_id ""ENSG00000243064""; gene_version ""10""; ...",126548
3369764,21,ensembl_havana,gene,46324124,46445769,.,+,.,"gene_id ""ENSG00000160299""; gene_version ""19""; ...",121645

# Calculate the mean and median of gene lengths

In [43]:
genes.describe()

              start           end   gene_length
count  1.929000e+04  1.929000e+04  1.929000e+04
mean   7.373146e+07  7.379912e+07  6.766304e+04
std    5.582533e+07  5.583178e+07  1.298385e+05
min    1.447500e+04  4.687000e+04  6.200000e+01
25%    3.110511e+07  3.114020e+07  9.739250e+03
50%    5.774250e+07  5.775770e+07  2.736300e+04
75%    1.103538e+08  1.104137e+08  7.086475e+04
max    2.489062e+08  2.489199e+08  2.473538e+06

# Find the top 10 longest genes

In [50]:
genes.sort_values(by=['gene_length'], ascending=False).head(10)

,seqname,source,feature,start,end,score,strand,frame,attribute,gene_length
2679474,16,ensembl_havana,gene,5239802,7713340,.,+,.,"gene_id ""ENSG00000078328""; gene_version ""23""; ...",2473538
1297140,7,ensembl_havana,gene,146116002,148420998,.,+,.,"gene_id ""ENSG00000174469""; gene_version ""23""; ...",2304996
1733179,9,ensembl_havana,gene,8314246,10613002,.,-,.,"gene_id ""ENSG00000153707""; gene_version ""19""; ...",2298756
1514121,X,ensembl_havana,gene,31097677,33339609,.,-,.,"gene_id ""ENSG00000198947""; gene_version ""18""; ...",2241932
1850816,11,ensembl_havana,gene,83455012,85627922,.,-,.,"gene_id ""ENSG00000150672""; gene_version ""18""; ...",2172910
1601567,8,ensembl_havana,gene,2935353,4994972,.,-,.,"gene_id ""ENSG00000183117""; gene_version ""20""; ...",2059619
3030998,20,ensembl_havana,gene,13995369,16053197,.,+,.,"gene_id ""ENSG00000172264""; gene_version ""18""; ...",2057828
1104549,6,ensembl_havana,gene,63719980,65707226,.,-,.,"gene_id ""ENSG00000188107""; gene_version ""15""; ...",1987246
2041854,10,ensembl_havana,gene,65912457,67763637,.,-,.,"gene_id ""ENSG00000183230""; gene_version ""18""; ...",1851180
2040306,10,ensembl_havana,gene,53802771,55627942,.,-,.,"gene_id ""ENSG00000150275""; gene_version ""20""; ...",1825171

# Find the lowest 20 shorest genes

In [51]:
genes.sort_values(by=['gene_length']).head(20)

,seqname,source,feature,start,end,score,strand,frame,attribute,gene_length
2913291,17,ensembl_havana,gene,43131208,43131270,.,+,.,"gene_id ""ENSG00000285057""; gene_version ""1""; g...",62
2118533,12,ensembl_havana,gene,93083598,93083675,.,-,.,"gene_id ""ENSG00000256393""; gene_version ""1""; g...",77
2362811,14,ensembl_havana,gene,22852616,22852728,.,-,.,"gene_id ""ENSG00000212335""; gene_version ""1""; g...",112
904441,4,ensembl_havana,gene,90838903,90839037,.,-,.,"gene_id ""ENSG00000187653""; gene_version ""11""; ...",134
1133423,6,ensembl_havana,gene,73373108,73373263,.,-,.,"gene_id ""ENSG00000235174""; gene_version ""1""; g...",155
129959,1,ensembl_havana,gene,27649419,27649610,.,+,.,"gene_id ""ENSG00000235912""; gene_version ""1""; g...",191
1847776,11,ensembl_havana,gene,82689559,82689768,.,+,.,"gene_id ""ENSG00000227097""; gene_version ""5""; g...",209
2938518,18,ensembl_havana,gene,52409042,52409257,.,+,.,"gene_id ""ENSG00000280098""; gene_version ""1""; g...",215
675285,3,ensembl_havana,gene,186596976,186597200,.,+,.,"gene_id ""ENSG00000283390""; gene_version ""1""; g...",224
988497,5,ensembl_havana,gene,62512246,62512482,.,-,.,"gene_id ""ENSG00000268942""; gene_version ""2""; g...",236
1967063,10,ensembl_havana,gene,29697935,29698174,.,+,.,"gene_id ""ENSG00000225976""; gene_version ""5""; g...",239
3255568,Y,ensembl_havana,gene,18992467,18992709,.,-,.,"gene_id ""ENSG00000185275""; gene_version ""6""; g...",242
3363759,21,ensembl_havana,gene,30718525,30718777,.,-,.,"gene_id ""ENSG00000231068""; gene_version ""1""; g...",252
2274799,12,ensembl_havana,gene,3211663,3211917,.,-,.,"gene_id ""ENSG00000227081""; gene_version ""5""; g...",254
1268412,7,ensembl_havana,gene,129410113,129410370,.,-,.,"gene_id ""ENSG00000238072""; gene_version ""1""; g...",257
105987,1,ensembl_havana,gene,152622834,152623103,.,-,.,"gene_id ""ENSG00000185962""; gene_version ""1""; g...",269
2594158,16,ensembl_havana,gene,26032539,26032811,.,-,.,"gene_id ""ENSG00000230330""; gene_version ""1""; g...",272
3363751,21,ensembl_havana,gene,30642864,30643136,.,+,.,"gene_id ""ENSG00000206104""; gene_version ""2""; g...",272
2526556,15,ensembl_havana,gene,29730713,29730985,.,+,.,"gene_id ""ENSG00000234664""; gene_version ""1""; g...",272
3363727,21,ensembl_havana,gene,30616425,30616699,.,+,.,"gene_id ""ENSG00000244624""; gene_version ""3""; g...",274

# Split attributes column on ‘;’ and create new dataframe, merge this onto the ens_gtf dataframe using pandas merge

In [68]:
genes2=genes["attribute"].str.split(";", expand=True)

In [69]:
genes2

,0,1,2,3,4,5
0,"gene_id ""ENSG00000160072""","gene_version ""20""","gene_name ""ATAD3B""","gene_source ""ensembl_havana""","gene_biotype ""protein_coding""",
132,"gene_id ""ENSG00000142611""","gene_version ""17""","gene_name ""PRDM16""","gene_source ""ensembl_havana""","gene_biotype ""protein_coding""",
361,"gene_id ""ENSG00000157911""","gene_version ""11""","gene_name ""PEX10""","gene_source ""ensembl_havana""","gene_biotype ""protein_coding""",
517,"gene_id ""ENSG00000157933""","gene_version ""10""","gene_name ""SKI""","gene_source ""ensembl_havana""","gene_biotype ""protein_coding""",
580,"gene_id ""ENSG00000142655""","gene_version ""13""","gene_name ""PEX14""","gene_source ""ensembl_havana""","gene_biotype ""protein_coding""",
...,...,...,...,...,...,...
3365880,"gene_id ""ENSG00000278903""","gene_version ""5""","gene_source ""ensembl_havana""","gene_biotype ""lncRNA""",,None
3365953,"gene_id ""ENSG00000237945""","gene_version ""9""","gene_name ""LINC00649""","gene_source ""ensembl_havana""","gene_biotype ""lncRNA""",
3367972,"gene_id ""ENSG00000188681""","gene_version ""13""","gene_name ""TEKT4P2""","gene_source ""ensembl_havana""","gene_biotype ""transcribed_unprocessed_pseudog...",
3368345,"gene_id ""ENSG00000243064""","gene_version ""10""","gene_name ""ABCC13""","gene_source ""ensembl_havana""","gene_biotype ""transcribed_unprocessed_pseudog...",
3369764,"gene_id ""ENSG00000160299""","gene_version ""19""","gene_name ""PCNT""","gene_source ""ensembl_havana""","gene_biotype ""protein_coding""",

In [70]:
genes

,seqname,source,feature,start,end,score,strand,frame,attribute,gene_length
0,1,ensembl_havana,gene,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ...",26083
132,1,ensembl_havana,gene,3069168,3438621,.,+,.,"gene_id ""ENSG00000142611""; gene_version ""17""; ...",369453
361,1,ensembl_havana,gene,2403964,2413797,.,-,.,"gene_id ""ENSG00000157911""; gene_version ""11""; ...",9833
517,1,ensembl_havana,gene,2228319,2310213,.,+,.,"gene_id ""ENSG00000157933""; gene_version ""10""; ...",81894
580,1,ensembl_havana,gene,10472288,10630758,.,+,.,"gene_id ""ENSG00000142655""; gene_version ""13""; ...",158470
...,...,...,...,...,...,...,...,...,...,...
3365880,21,ensembl_havana,gene,6318378,6360415,.,+,.,"gene_id ""ENSG00000278903""; gene_version ""5""; g...",42037
3365953,21,ensembl_havana,gene,33915534,33977703,.,+,.,"gene_id ""ENSG00000237945""; gene_version ""9""; g...",62169
3367972,21,ensembl_havana,gene,9068325,9129773,.,-,.,"gene_id ""ENSG00000188681""; gene_version ""13""; ...",61448
3368345,21,ensembl_havana,gene,14236206,14362754,.,+,.,"gene_id ""ENSG00000243064""; gene_version ""10""; ...",126548
3369764,21,ensembl_havana,gene,46324124,46445769,.,+,.,"gene_id ""ENSG00000160299""; gene_version ""19""; ...",121645

In [71]:
genes3 = genes.join(genes2)

In [72]:
genes3

,seqname,source,feature,start,end,score,strand,frame,attribute,gene_length,0,1,2,3,4,5
0,1,ensembl_havana,gene,1471765,1497848,.,+,.,"gene_id ""ENSG00000160072""; gene_version ""20""; ...",26083,"gene_id ""ENSG00000160072""","gene_version ""20""","gene_name ""ATAD3B""","gene_source ""ensembl_havana""","gene_biotype ""protein_coding""",
132,1,ensembl_havana,gene,3069168,3438621,.,+,.,"gene_id ""ENSG00000142611""; gene_version ""17""; ...",369453,"gene_id ""ENSG00000142611""","gene_version ""17""","gene_name ""PRDM16""","gene_source ""ensembl_havana""","gene_biotype ""protein_coding""",
361,1,ensembl_havana,gene,2403964,2413797,.,-,.,"gene_id ""ENSG00000157911""; gene_version ""11""; ...",9833,"gene_id ""ENSG00000157911""","gene_version ""11""","gene_name ""PEX10""","gene_source ""ensembl_havana""","gene_biotype ""protein_coding""",
517,1,ensembl_havana,gene,2228319,2310213,.,+,.,"gene_id ""ENSG00000157933""; gene_version ""10""; ...",81894,"gene_id ""ENSG00000157933""","gene_version ""10""","gene_name ""SKI""","gene_source ""ensembl_havana""","gene_biotype ""protein_coding""",
580,1,ensembl_havana,gene,10472288,10630758,.,+,.,"gene_id ""ENSG00000142655""; gene_version ""13""; ...",158470,"gene_id ""ENSG00000142655""","gene_version ""13""","gene_name ""PEX14""","gene_source ""ensembl_havana""","gene_biotype ""protein_coding""",
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3365880,21,ensembl_havana,gene,6318378,6360415,.,+,.,"gene_id ""ENSG00000278903""; gene_version ""5""; g...",42037,"gene_id ""ENSG00000278903""","gene_version ""5""","gene_source ""ensembl_havana""","gene_biotype ""lncRNA""",,None
3365953,21,ensembl_havana,gene,33915534,33977703,.,+,.,"gene_id ""ENSG00000237945""; gene_version ""9""; g...",62169,"gene_id ""ENSG00000237945""","gene_version ""9""","gene_name ""LINC00649""","gene_source ""ensembl_havana""","gene_biotype ""lncRNA""",
3367972,21,ensembl_havana,gene,9068325,9129773,.,-,.,"gene_id ""ENSG00000188681""; gene_version ""13""; ...",61448,"gene_id ""ENSG00000188681""","gene_version ""13""","gene_name ""TEKT4P2""","gene_source ""ensembl_havana""","gene_biotype ""transcribed_unprocessed_pseudog...",
3368345,21,ensembl_havana,gene,14236206,14362754,.,+,.,"gene_id ""ENSG00000243064""; gene_version ""10""; ...",126548,"gene_id ""ENSG00000243064""","gene_version ""10""","gene_name ""ABCC13""","gene_source ""ensembl_havana""","gene_biotype ""transcribed_unprocessed_pseudog...",
3369764,21,ensembl_havana,gene,46324124,46445769,.,+,.,"gene_id ""ENSG00000160299""; gene_version ""19""; ...",121645,"gene_id ""ENSG00000160299""","gene_version ""19""","gene_name ""PCNT""","gene_source ""ensembl_havana""","gene_biotype ""protein_coding""",

In [73]:
genes3.shape

(19290, 16)

In [74]:
genes2.shape

(19290, 6)

In [75]:
genes.shape

(19290, 10)